services:
  - type: web
    name: caresync-backend
    env: node
    plan: free
    buildCommand: npm install --prefix backend
    startCommand: npm start --prefix backend
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
